### ISSUE TITLE
Electric Oven

### ISSUE THREAD

**Issue by pip69** [blay09/CookingForBlockheads#108]
As the title, but there should also be simpler options.
Old fashioned stove could less internal space, and cheaper to make.
Coldbox cheaper to make, won't connect with itself.

RF Stove would be the same as is.  Maybe add to the cooking table what's is being cooked in the stove.
RF Fridge could get some enhancements; makes snowballs for recipes with a sink, auto pulls items from the stove when done.  An option to sort multiple fridges, if there are items in more than 1 locations, it'll move all items to the fridge that has the most to start with that also has room for all of it.

**Comment by ThePreviousOne** [comment]
how about an interface block that could handle those types of requests allowing you to process or store Items via other mods while maintaining the multiblock functionality?

**Comment by othermusketeer** [comment]
The external heater from Immersive Engineering works with the oven. However, I did notice that when I was baking a stack of bread, when it finished, some of the toast "stayed in the oven area" (the central area), which triggered the external heater to run non stop.

**Comment by AnthonyKane5528X** [comment]
You could always integrate this into the configs.  If Cooking for Blockheads detects and RF using mod (or EU for that matter) you can enable the "use RF/t" feature so that the oven and Fridge require RF to work.  This would allow people to use the mod without RF if the download it separately or enable RF use if its in a larger modpack that has power gen.

You would have to find some trade off for having a refrigerator being powered by RF though.  Currently its just a vertical double chest, and minecraft has no mechanics (by default) regarding food spoilage.

**Comment by BlayTheNinth** [comment]
The next version will have an upgrade that can be applied to an oven to make it accept energy and run off that instead. The snowball fridge thing is implemented as an upgrade to the fridge and will not require energy as I don't want to lock features behind energy requirements. 

I don't feel like adding "variant blocks" providing the same functionality fits this mod, I'd rather keep a simple "one block = one function" rule (at least for those that aren't visually different things). The upgrade items seem like a good compromise.

Fridge sorting is out of scope for this mod and can be achieved through other means (e.g. my other mod Refined Relocation, or just normal piping), especially with the upcoming preservation chamber upgrade that will make the fridge no longer fully empty out slots.
