### ISSUE TITLE
Rendering issue with Item Physics Lite mod

### ISSUE THREAD

**Issue by patrickclank9** [blay09/CookingForBlockheads#110]
Basically, [this](http://i.imgur.com/x9RJ0Is.gif) happens when rendering the items on the oven/tool rack while [Item Physics](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2076336-itemphysic-1-2-4-more-realtistic-items-stone) is installed.

**Comment by blay09** [comment]
That's hilarious. xD

**Comment by blay09** [comment]
Will be fixed on 1.8.9+ (and I think is already fixed on 1.7.10 Jenkins builds)

**Comment by Poeschl** [comment]
Unfortunately not fixed in the latest version of your Jenkins.

For some reason I'm not able to setup the gradle project for the 1.7.10 version, but there is already a easy fix from a other mod: https://github.com/Esteemed-Innovation/Flaxbeards-Steam-Power/commit/a9fc6de01ee70d5c4f0d20f1669395b703d580b1
