### ISSUE TITLE
[FREQ] Give better hint for fridge dying process

### ISSUE THREAD

**Issue by Syndaryl** [blay09/CookingForBlockheads#155]
Holding dye in hand and left, right, shift-left, or shift-right clicking does not dye the fridge. I accidentally tried control-clicking, and found the secret.
Perhaps expand on the 'Dyable!' note?

**Comment by BlayTheNinth** [comment]
Control-clicking? o_o It should just work via normal right clicking and it does so for me. This might be something only affecting some people (there have been others who were weirdly confused about how to dye the fridge). Are you using default controls? Do you have anything bound to control? This is weird.

**Comment by Syndaryl** [comment]
Right clicking simply opens the fridge, whether I have an item in hand or not. Left clicking attempts to "mine" the fridge. Shift-clicking (either) doesn't help.
Left control is bound to sprint, left shift is bound to Sneak. 

I'm running Forge 12.18.1.2018, and a fair amount of mods but none have any commands on left control or left shift (More adding new blocks and entities, and I've ruthlessly gone through and curated keybinds because I'm neurotic like that.).

Here's my modlist, in case it ends up helping - http://pastebin.com/QffFC3Pz

**Comment by BlayTheNinth** [comment]
Are you using Vanilla dye items?

**Comment by Syndaryl** [comment]
Vanilla dye, yup. I was trying Ink sacks.

**Comment by BlayTheNinth** [comment]
I can't reproduce this issue and there's nothing that would indicate it's a problem with this mod in particular. Simply right-clicking with dye seems to work for everyone else (as it should, since it acts on the same function as the opening of the fridge or a chest). I tried running it with some of the mods you mentioned in your list, and had no issues. If you can upload me a zip-file of the pack you're using (including configs and options.txt) I could have another look.
