### ISSUE TITLE
Certain foods (that should be craftable) won't craft in kitchen gui

### ISSUE THREAD

**Issue by eriico39hi** [blay09/CookingForBlockheads#167]
Jelly from Pam's used to be craftable, now it is not.

Using version 4.2.14

When it is clicked the message "click again to craft pops up" but when clicked again it doesn't craft, nor does it show the recipe in the left panel.

![image](https://cloud.githubusercontent.com/assets/19679613/18207736/64669704-70fa-11e6-98c9-809ff633c118.png)

There are some other recipes this seems to happen to as well such as fruit salad, cranberry sauce, caramel, and taffy.

**Comment by krasnyineko** [comment]
I can confirm I am also having this same issue in a modpack I am using called All The Mods v18c which updated to 4.2.14

[Cooking For Blockheads version 1.10.2-4.2.14 not working as intended](https://github.com/whatthedrunk/allthemods/issues/164)

**Comment by Aelrath** [comment]
I also experienced this with version 4.2.14. Another hint to the cause is that most recipes with firm tofu that ore dictionary is substitute for most meats you can't craft any recipe as @eriico39hi described, unless you have some of the actually ingredients (e.g. bacon and eggs + skillet) in your storage then the recipe can be crafted. The new locking of ingredients feature in the recipe window seems to be causing it.

**Comment by mrtomwolf** [comment]
Same issue.

I can make apple juice but not pear juice so it's not the process but the ingredients that seems to be the issue.
