### ISSUE TITLE
[SF3] Some recipes not having arrow to flip between options

### ISSUE THREAD

**Issue by Lethann** [blay09/CookingForBlockheads#194]
Skyfactory 3

Easiest to see this on is Chocolate Milk. It has option for Bucket of milk, fresh milk, and soy milk. Other recipes have the arrow to flip between the options to choose what you use but this (and many others) still flip quickly like in NEI/JEI so it's impossible to tell what it's using. 

![cfbchocolatemilk](https://cloud.githubusercontent.com/assets/25929754/23305226/59836de2-fa63-11e6-8fe4-cf7bc673c040.gif)

**Comment by BlayTheNinth** [comment]
This is the handling for ore-dictionary items, which is different from multiple recipes resulting in the same (which is what the arrows are used for).

It's meant to switch way slower than it currently does (which was fixed in the latest version of the mod).

You can click the flipping item to lock it to that type, and also use the scroll wheel on it to pick one of the options.

**Comment by Lethann** [comment]
oh cool! I didn't know that. Kinda wish there was an 'Info' tab in the book or something that had those instructions ingame as well as how to properly setup the kitchen. Still. I really REALLY love this mod!!!
