### ISSUE TITLE
Suggestion: Freezer Block

### ISSUE THREAD

**Issue by DrGirlfriend** [blay09/CookingForBlockheads#229]
Would be nice to have a freezer block that stacked like the refrigerator (2 freezers on top of each other) or is able to stack on top of one refridgerator block

Maybe even an integrated ice machine for recipes that call for ice/snow

**Comment by BlayTheNinth** [comment]
I think what I'll do is make the freezer a non-stackable block that has the size of two chests by default, allowing for denser storage. The Ice Machine will likely be an upgrade for it.

**Comment by BlayTheNinth** [comment]
Decided against the seperate freezer block in the end since I think adding variations of blocks that provide basically the same functionality and look nearly the same would just unnecessarily bloat the mod.

Note that the fridges can be dyed, so you could just dye your designated "freezer" a different color than your normal fridges (that's what I was going to do for the freezer block before I decided against adding it).

The ice machine thing will be an upgrade for the fridge instead and releasing in the next version.
