### ISSUE TITLE
Missing the required element 'version' 

### ISSUE THREAD

**Issue by PhoenixRiver** [blay09/CookingForBlockheads#256]
Version: CookingForBlockheads_1.12.1-6.3.17

This error comes up when loading:

[main/WARN] [cookingforblockheads]: Mod cookingforblockheads is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 6.3.17

Hope this helps :)

**Comment by BlayTheNinth** [comment]
The warning doesn't really mean anything or have any negative effect. In fact, it's a pretty dumb warning and it really shouldn't be there in the first place - it might just be some legacy leftover. Since FML will likely be getting a rewrite, this'll probably solve itself by then.

Until then, it can be safely ignored.
