### ISSUE TITLE
Gas Oven

### ISSUE THREAD

**Issue by WrongWeekend** [blay09/CookingForBlockheads#275]
Powering the oven directly with electricity/energy has already been suggested but it would also be useful to be able to heat it using piped-in hot/flammable fluids like lava, steam, gas, or ethanol. I wouldn't count Harvestcraft's cooking oil as an example of this due to it being in item form.

**Comment by BlayTheNinth** [comment]
Moved the jar thing into a seperate issue: https://github.com/blay09/CookingForBlockheads/issues/277

**Comment by BlayTheNinth** [comment]
I'm not sure about this one yet, I feel it would only be used by an extremely tiny amount of people since the energy-based version is so much simpler, so it might not be worth the work/maintenance/bloat. Especially since those fluids/gases can already be used to power the upcoming energy-based oven, just that they need another engine block in between.

**Comment by unmoving-javi** [comment]
Honestly I like this one, would make the kitchen a little bit nicer for low-tech gameplay. Lava fuel techincally works in furnaces already, but if you don't use it all up, it just gets wasted, so I would definitely appreciate a lava-fuelled stove.
