### ISSUE TITLE
Missing version.properties file 

### ISSUE THREAD

**Issue by Thanatosus** [blay09/CookingForBlockheads#293]
Hello,

It seems that your mod missing the version.properties file

*[11:21:33] [Server thread/WARN] [FML]: Mod cookingforblockheads is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 6.4.36*

Is it planed to add this file in the feature ?

Thank you for your work on Cooking,
Have a good day,
Thanatosus

**Comment by BlayTheNinth** [comment]
This is not an error, Forge is just falsely reporting it as warning instead of a normal debug notice. The metadata version is correct and apart from that one line in the log, everything will be working correctly as expected.

This will most likely solve itself during the FML rewrite in Minecraft 1.13.
