### ISSUE TITLE
Fruit basket slow rendering

### ISSUE THREAD

**Issue by panoskj** [blay09/CookingForBlockheads#326]
I have noticed fruit baskets can be a significant performance hit. For example, in my base, I have a kitchen with 10 baskets. Even when looking towards them from a distance, behind solid blocks, they still take up 30-50% of the rendering time (according to shift + F3). Changing video settings didn't improve performance.

Version: 6.4.62
Forge Version: 14.23.4.2759

**Comment by BlayTheNinth** [comment]
It's normal for ten of them in the same area to be a performance hit. They render their content, which is up to 27 items, resulting in up to 270 items for ten, and due to the way item rendering in Minecraft works this happens on every frame.

They're meant to be a visual gimmick, not mass storage. Counters and fridges work differently in that they only have to render their content when the door is open, meaning they don't have this effect.

**Comment by panoskj** [comment]
Honestly that's what I thought too. What bugged me the most was finding which mod/item was responsible for this at first place, maybe you could add a warning in their description. Alternatively you could find a way to bake the model with the items and cache it but that would require further research.

**Comment by BlayTheNinth** [comment]
A warning would unnecessarily scare users who are just thinking of getting one or two of them. Item rendering being slow is generally known in Modded Minecraft (or learnt through cases such as this one).

Going the whole way of baking item models into the model would be way out of scope, and still risk hurting performance as it would have to be rebuilt on every change (=> item crafted in cooking table).
