### ISSUE TITLE
Wireless RF Heating Coil is consumed in the oven

### ISSUE THREAD

**Issue by Sunekaer** [blay09/CookingForBlockheads#339]
The Wireless RF Heating Coil from extra util 2 is getting consumed in the oven

https://github.com/Sunekaer/stoneBlock/issues/522

**Comment by BlayTheNinth** [comment]
It is not getting consumed, it is just getting desynced because on the client-side, Extra Utilities always claims the coil has a fuelTime of 20, but on the server-side it returns the proper value, making it a non-fuel item if the coil has no power.

That results in the item never actually being placed inside the slot - it is only there visually, causing your inventory to desync with the server. The same problem happens with Vanilla furnaces, which is why the item is dropped when you put it in the slot and then close the GUI (without clicking anywhere else).

Either the item got dropped or the inventory was desynced, in which case opening a chest usually helps.
