### ISSUE TITLE
[Suggestion] Recipes restricted to CfB blocks

### ISSUE THREAD

**Issue by D-Fink** [blay09/CookingForBlockheads#378]
It would be nice if these blocks replaced the crafting table recipes so you **have to** use the blocks from this mod in order to make food.

**Comment by Skydragonsz** [comment]
Hmmm, nice idea! 

I would suggest to this being an optional setting if it would be implemented. (We don't want to force people)

**Comment by BlayTheNinth** [comment]
I'd even go as far as making it an addon mod since it strives so far off from what's Cooking for Blockhead's main purpose is. But realistically I don't think I will be going for that, as I can't even keep up with my current mods at the moment. If someone else wants to make a mod like that, I can help out by making sure CFB exposes the necessary API endpoints though.
