### ISSUE TITLE
Some ingredients show as not available but are

### ISSUE THREAD

**Issue by TheRealDadbeard** [blay09/CookingForBlockheads#382]
So I have the salt in my inventory but it shows that I don't have it but can craft the recipe without any issues. This problem is for other ingredients too.

forge-1.12.2-14.23.5.2838
CookingForBlockheads_1.12.2-6.4.71

![2019-07-03_19 03 38](https://user-images.githubusercontent.com/23340600/60610923-54e62d80-9dc5-11e9-823c-71d9992dfae6.png)

**Comment by katubug** [comment]
Just as another data point, my modpack is having this same issue. In our case, it happens with salt and butter both in an adjacent refrigerator, and in the player's inventory. I apologize if this is not helpful, since you already have this issue reported for the same versions, but I thought I'd post it just in case.

* **Minecraft version:** 1.12.2
* **Forge version:** forge-1.12.2-14.23.5.2838-universal
* **Modpack version** (links to current modlist): [1.7.2](http://enthusiasticraft.cf/modpack-update-1-7-2/#modlist)
* **Mod versions:** CookingForBlockheads_1.12.2-6.4.71, Pam's HarvestCraft 1.12.2zf
