### ISSUE TITLE
Fridge causes crash on placement (Solution: update Forge to latest version)

### ISSUE THREAD

**Issue by BigBoi1234321** [blay09/CookingForBlockheads#406]
every time i place a fridge in any world it crashes

**Comment by Ichirou-Tomoe** [comment]
This bug concern the new 1.14 version, but it doesn't happen with the latest version of Forge, so you can just add a recommendation to use it.
I tested it with the latest (forge-28.1.87) and it works fine, but the game crash with the two other version I tested: the recommended version forge-28.1.0 and the version I was using forge-28.1.31.
I included minecraft's report file if you're curious, but since it works with the latest forge, you obviously don't need to investigate it further.
[crash-2019-11-12_18.24.40-client.txt](https://github.com/blay09/CookingForBlockheads/files/3837466/crash-2019-11-12_18.24.40-client.txt)
