### ISSUE TITLE
Add Minetweaker Compatibility:

### ISSUE THREAD

**Issue by talonos2** [blay09/CookingForBlockheads#48]
Currently, the cooking book and related GUIs allow you to view (and even craft using) recipes that no longer exist after having been altered with MineTweaker.

To reproduce:

Use this minetweaker script: 

recipes.remove(<minecraft:bread>);
recipes.addShapeless(<minecraft:bread>, [<minecraft:dirt>]);

You can verify it works by turning dirt into bread using the crafting grid in your inventory.

Open a cooking for blockheads book. Give yourself a dirt. It will not tell you that you can craft bread. Give yourself three wheat. It will tell you that you can make bread. With volume 2 open, you can even craft bread with the non-existent ingredients.

It would be awesome for modpack makers if this were fixed.

**Comment by blay09** [comment]
In order to fix this correctly I will need the above mentioned PostReloadEvent from MineTweaker's side, but for now I've made the mod reload its food recipe cache on world load (so *after* MineTweaker changes are applied) if MineTweaker is installed.

Note that changes applied using the MineTweaker /mt reload command won't be available to the cooking book/table until the world was re-loaded.

**Comment by jaredlll08** [comment]
Do you still want the event in MT?

**Comment by blay09** [comment]
@jaredlll08 Yes.

**Comment by talonos2** [comment]
You guys are terrific for doing this. Thanks again.
