### ISSUE TITLE
Farmer's delight support

### ISSUE THREAD

**Issue by SimonMeskens** [blay09/CookingForBlockheads#492]
Support for Farmer's Delight would be really cool, but it seems like it would need a custom module to support the special crafting blocks it uses. To me it's the best cooking mod out there though, so I think it'd be worth it.

**Comment by jecowa** [comment]
Here's a data pack thing to help get Farmer's Delight support started (not sure if intermediate ingredients belong on the GENERAL list, though. If not, remove "rice" and "milk_bottle" from the top of the general list and remove "rice_panicle" from the top of the ingredients list):

{
  "modid": "farmersdelight",
  "foods": {
    "GENERAL": [
      "farmersdelight:rice",
      "farmersdelight:milk_bottle",
      "farmersdelight:hot_cocoa",
      "farmersdelight:apple_pie",
      "farmersdelight:sweet_berry_cheesecake",
      "farmersdelight:chocolate_pie",
      "farmersdelight:roast_chicken_block",
      "farmersdelight:stuffed_pumpkin_block",
      "farmersdelight:honey_glazed_ham_block",
      "farmersdelight:shepherds_pie_block"
    ],
    "INGREDIENTS": [
      "farmersdelight:rice_panicle",
      "farmersdelight:rice",
      "farmersdelight:milk_bottle"
    ]
  },
  "kitchenItemProviders": [
    "farmersdelight:basket",
    "farmersdelight:pantry"
  ]
}

But there's also still this special cooking appliance that Farmer's Delight adds called a Cooking Pot. It's like a Crafting Table combined with a Furnace and has a slot for Bowls or Glass Bottles to go in. It would be cool if the Cooking Table could insert items into the Cooking Pot like it does with the Oven.

The only other things I know of that you might possibly add support for are the Stove and the Cutting Board. The Stove is just a Campfire that holds 6 items instead of 4. But Cooking for Blockheads doesn't support the vanilla Campfire, so maybe it doesn't make sense to support the Farmer's Delight Stove.

The other thing is the Cutting Board. You can place one of the many cakes or a pumpkin or a melon on the Cutting Board and click it with a knife to cut it into slices. Not sure how important supporting the Cutting Board is. Might be kind of cool though to craft a cake and immediately send it to the cutting board.

**Comment by SimonMeskens** [comment]
The cutting board is actually required for many of the cooking recipes, it's not just for slicing stuff.

**Comment by BlayTheNinth** [comment]
Basic support has been added via #542, but I'm not really sold on supporting the special crafting blocks yet.

It feels like it kind of defeats the point of Farmer's Delight to just have its in-world crafting be performed automatically.

Moving this over to Discussions for now.
