### ISSUE TITLE
Crash with Tardis mod on server startup

### ISSUE THREAD

**Issue by 1nd1r4** [blay09/CookingForBlockheads#547]
**Versions**
- Minecraft Version: 1.16.5
- Forge Version: 36.2.8 (over mohist-1.16.5-811)
- Mod Version: 9.3.4
- Do you use Sponge, OptiFine or Vivecraft (and which?): Server is running over Mohist.

**Describe the bug**
Server crashes on startup. See Log.

**To Reproduce**
1. Use Tardis-Mod-1.16.5-1.5.1 with CookingForBlockheads
2. start server
3. server crashes without crash-report.

**Expected behavior**
No crash.

**Log**
[latest.log](https://github.com/ModdingForBlockheads/CookingForBlockheads/files/7309049/latest.log)

**Comment by Unixkitty** [comment]
It seems that this is the same issue I reported some time ago: https://github.com/ModdingForBlockheads/CookingForBlockheads/issues/543

**Comment by BlayTheNinth** [comment]
@50ap5ud5 I think I found the problem:

https://gitlab.com/Spectre0987/TardisMod-1-14/-/blob/1.16/src/main/java/net/tardis/mod/events/CommonEvents.java#L674 and https://gitlab.com/Spectre0987/TardisMod-1-14/-/blob/1.16/src/main/java/net/tardis/mod/events/CommonEvents.java#L682

In your reload listeners you call `thenRunAsync`. This causes all reload listeners after yours to run on the `CompletableFuture.ASYNC_POOL` which seems to be causing classloading issues that eventually result in the above crash.

Using `thenRun` instead avoids the problem. If you actually do need them to be async you should pass your own Executor to make sure it doesn't use the default one, since the default one seems to have a different parent class loader than mod/mc classes.

(https://gitlab.com/Spectre0987/TardisMod-1-14/-/merge_requests/67)

**Comment by BlayTheNinth** [comment]
Closing since this is just waiting on a Tardis update
