### ISSUE TITLE
Remainders other than buckets get voided

### ISSUE THREAD

**Issue by JaisDK** [blay09/CookingForBlockheads#568]
https://github.com/ModdingForBlockheads/CookingForBlockheads/blob/1.18.x/shared/src/main/java/net/blay09/mods/cookingforblockheads/registry/CookingRegistry.java#L355

I don't know why you've chosen to only support buckets as remaining item from a crafting operation, other ingredients or containers can also have a remainder. With this check you're voiding those items.

**Comment by BlayTheNinth** [comment]
Honestly, I don't remember why I limited it to buckets either. I found this diagram called theproblem.png from 2016 and I'm sure it made a lot of sense back then.

![theproblem](https://github.com/TwelveIterationMods/CookingForBlockheads/assets/1933180/a7049887-8dd0-4f29-b55a-deca7d499507)

(I believe buckets needed extra special support because the sink can provide water to recipes in the form of water buckets and would have resulted in infinite buckets - so remainder items worked at some point - not sure when they stopped working)

Blocked by #673 because the API rewrite will touch and resolve this as well

**Comment by BlayTheNinth** [comment]
Actually testing with honey bottles => honey blocks right now and can't reproduce this. I'm receiving empty bottles just fine. In fact, the code linked originally was specifically code for avoiding duplicate buckets **because** the mod would return remainder items. I don't think there was any issue here in the first place.
