### ISSUE TITLE
Allow placement of farmer's delight cutting boards on CFB counters

### ISSUE THREAD

**Issue by 0DeltaWaves** [blay09/CookingForBlockheads#624]
Not sure if this would be the same issue as #562, but I would very much like to be able to have farmer's delight cutting boards on CFB counters. As it is currently, you have to put it off to the side somewhere to avoid breaking the link between CFB blocks.

**Comment by ItsKryi** [comment]
I second this.  I think part of the issue is that very few things can be placed on Cooking for Blockhead counters that are not in the CFB mod.  I cannot place Minecraft lantern, candles and other mod related items.. but I can place a flower pot and skeleton head (although they both are floating a little).   I can actually place the Farmer's Delight Skillet and Pot as well.  So it seems like some items are being blocked, others are not.  I hope this helps narrow down what the issue might be.

**Comment by BlayTheNinth** [comment]
This is the unfortunate side effect of the counter blocks being slightly lowered, and it's not possible to affect other blocks' models in the same way that e.g. the toaster lowers itself. Maybe there will be full block variants of the counters at some point, but for now, this is not possible.
