### ISSUE TITLE
Possibility for Functional Storage support?

### ISSUE THREAD

**Issue by K-B-X-C-N** [blay09/CookingForBlockheads#634]
Much like the functionality between Storage Drawers, but for Functional Storage. If no/no plans, completely understand.

**Comment by BlayTheNinth** [comment]
Unfortunately this is not possible right now, as Functional Storage block entities do not support capability attachments due to not delegating to Forge's `super.getCapability()` and instead always falling back to `LazyOptional.empty`.

You could report this to Functional Storage as it could be considered a bug.

**Comment by BlayTheNinth** [comment]
Closing here since there's nothing more to be done on CFB side.
