### ISSUE TITLE
Cow in a Jar cannot be obtained

### ISSUE THREAD

**Issue by SheReyy** [blay09/CookingForBlockheads#681]
### Minecraft Version

1.20.1 (LTS)

### Mod Loader

Forge

### Mod Loader Version

Forge 47.2.16

### Mod Version

cookingforblockheads-forge-1.20-16.0.1.jar

### Balm Version

balm-forge-1.20.1-7.2.1.jar

### Describe the Issue

After dropping an anvil on a cow that's standing over a Milk Jar, the Cow in a Jar item is not created, and the Smithing Table SFX can be heard. Also the recipe shown by REI is a bit buggy. Searching for the Cow in a Far recipe, shows only the Blook Loot Drop page. Searching for the uses of the Cow in a Jar, shows a a recipe which does not include the cow, only the Cow in a Jar and an Anvil/Milk Jar. This can be seen in the attached video.

Edit: cowJarEnabled is set to true in the config file

Attachment video: https://streamable.com/qbb1tj

### Logs

https://gist.github.com/IamRyan30/f6c8d142c3463124f3191965983f1f27

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

mbeddium-0.2.16+mc1.20.1.jar, ferritecore-6.0.1-forge.jar, smoothboot-mc1.20.1-0.0.3.jar, entityculling-forge-1.6.2-mc1.20.1.jar,

**Comment by BlayTheNinth** [comment]
Cooking for Blockheads does not play a smithing table sound when jarring a cow. You likely have some mod installed that tries to do similar methods of "drop anvil on entity" crafting and completely hijacks the event in return.

**Comment by QueenCorbeau** [comment]
I'm having the same problem in 1.20.1 in the Fantasy Skies modpack. The problem seems to be - and I don't know if this is just with this mod or with some cross compatibility issue - that the cow doesn't stand on top of the jar. Its legs come down on either side of the jar, so when the anvil falls, the cow isn't in the right place to force it into the jar; they are instead in the same blockspace. I have tried every method I can think of to get the cow to stay one block up on top of the jar, but it will not. The pack has the option of buying cow spawn eggs, so my workaround was to buy the egg, make the jar, then delete both and just cheat in the cow-in-a-jar, but that doesn't seem feasible long-term. 

I know the pack has about 450 mods, so I'm not sure how to even start tracking down which mod could be causing this if it's not native to Cooking for Blockheads.

**Comment by kezmodius** [comment]
I am also having the same issue on my 1.20.1 server. The sound played when the cow gets hit by the anvil is the breaking anvil sound and the anvil goes straight back into my inventory and the cow is hurt. Mod pack is: https://www.curseforge.com/minecraft/modpacks/minecolonies-medieval-magick

**Comment by BlayTheNinth** [comment]
Some possible causes:
- `cowJarEnabled` might be disabled in the config
- some other mod might be replacing anvils or their damage source
- some other mod might be hijacking anvil damage events without giving other mods a chance
- some other mod is replacing cows in a way that Cooking for Blockheads cannot detect

It's unlikely to be the position of the cow because even if no milk jar is found, Cooking for Blockheads still removes the cow and plays a chicken pop sound. If the cow remains and only gets hurt instead, it means Cooking for Blockheads never got to run its code.
