### ISSUE TITLE
Weirdly ignoring resourcepack structure

### ISSUE THREAD

**Issue by Luningor** [blay09/CookingForBlockheads#702]
As stated.
I've started making a resourcepack for this mod. No issues other than my incompetence up until I started noticing incoherences: the fridge had two individual models, the cow bottle took a separate model as a default. Up until then, fine, I thought. It must be the way it's coded, as far as I knew. No matter, I'll find a workaround. Yet at the same time, I found none. I couldn't even remodel the cow jar and the normal milk jar separately, as they both seemed to default to the milk_jar.json named model. 
My request is, in short:
Please make it so that the mod is properly compatible with resourcepacks, or please give us a sample resourcepack to build upon (to be noted, I already tried the one embedded in the .jar). I'd love to be able to customize this mod's look.

The resourcepack I'm talking about: [Luni's Perfect Cooking.zip](https://github.com/TwelveIterationMods/CookingForBlockheads/files/15226711/Luni.s.Perfect.Cooking.zip)

**Comment by BlayTheNinth** [comment]
The blockstate for the milkjar in your resource pack is invalid. The keys have to match those of the original, since that's the values Minecraft uses to pick the correct model. Normally, you shouldn't have to edit any of the blockstates - they already take care of applying rotations without needing a separate model for each rotation.

To better account for changes like yours, I've now added a separate cow_jar_liquid model that will be used for the milk in a cow jar, and made it so the liquid actually gets rotations applied to them.

However, there's also things that are not feasible to be changed due to Minecraft limitations, such as the mismatching bounding boxes or the special item rendering (like toast in a toaster) that strongly depends on the original model dimensions.

**Comment by Luningor** [comment]
Thank you so much! I'll be sure to send you a copy of the finished pack once I try this on. Also, for the bounding boxes or the rendered toasts, don't you worry: I've accounted for it. Still, thanks again for entertaining this request!
